env:
  CCACHE_DIR: "/tmp/.ccache"
  PORTS_BRANCH: "2026Q1"

common: &COMMON

    timeout_in: 90m

task:
    name: FreeBSD 15 binaries
    alias: bins
    compute_engine_instance:
      image_project: freebsd-org-cloud-dev
      image: freebsd-15-0-release-amd64-ufs
      platform: freebsd
      cpu: 4
      memory: 8G
      disk: 40 #GB
    <<: *COMMON

    portstree_cache:
      folder: /usr/ports/
    ccache_cache:
      folder: ${CCACHE_DIR}
    pkg_cache:
      folder: /var/cache/pkg/
     
    run_script:
      - |
       ./.ci/run.sh

    bins_artifacts:
      path: "./**/*"
